name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main   # runs workflow whenever code is pushed to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # Permissions needed for GitHub Container Registry
    permissions:
      contents: read
      packages: write

    steps:
      # 1. Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx (modern builder with caching support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Authenticate to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Build and push Docker image to GHCR
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/github-actions-project:latest
